channels:
- conda-forge
dependencies:
- python=3.13.0
- pip<=24.2
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==2.2.2
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xgboost==3.0.0
name: mlflow-env
